### ISSUE TITLE
Yandex Database права на директорию

### ISSUE THREAD

**Issue by gayratv** [ydb-platform/ydb-nodejs-sdk#101]
В Yandex Database NodeJS SDk в примере есть непонятный для меня фрагмент по назначению прав:

https://github.com/ydb-platform/ydb-nodejs-sdk/blob/master/examples/scheme-client/index.ts#L20

```
await driver.schemeClient.modifyPermissions(
        'example-path/subpath',
        [{
            grant: {
                subject: 'tsufiev@staff',
                permissionNames: ['read', 'use']
            }
        }]
    );
```
В документации по поводу управления доступом нашел только раздел: Управление доступом в Yandex Database

https://cloud.yandex.ru/docs/ydb/security/start_auth

но там речь ведется про пользователей Yandex облака.

Расскажите пожалуйста - в вышеприведенном примере кому даются права и на что они влияют ?

**Comment by Ulibka68** [comment]
tsufiev@staff - это должен быть зарегистрированный пользователь в моем Яндекс облаке ?

https://console.cloud.yandex.ru/iam?section=users

(т.е. сначала надо добавить пользователя - потом давать ему права ?)

**Comment by Ulibka68** [comment]
Andrey Fomichev
дал ответ на мой вопрос тут:
[stackoverflow](https://ru.stackoverflow.com/questions/1353391/yandex-database-%d0%bf%d1%80%d0%b0%d0%b2%d0%b0-%d0%bd%d0%b0-%d0%b4%d0%b8%d1%80%d0%b5%d0%ba%d1%82%d0%be%d1%80%d0%b8%d1%8e)

Цитата:
В YDB есть гранулированные права на подобъекты базы, например, на директории и/или таблицы. 
В данном примере права выдаются объекту в поле subject. 
Конкретные права описаны в поле permissionNames. @staff -- это имена внутренних инсталляций YDB, в YandexCloud они не поддерживаются.
