### ISSUE TITLE
withRetries - что означают параметры для RetryParameters

### ISSUE THREAD

**Issue by gayratv** [ydb-platform/ydb-nodejs-sdk#126]
При вызове withRetries  в нее вторым параметром передаются параметры для создания стратегии повтрения.

Среди этих параметров есть параметры backoffCeiling и backoffSlotDuration

Объясните пожалуйста - что они означают ?

**Comment by nikolaymatrosov** [comment]
Это параметры для стратегии экспоненциального ретрая.
Смысл этих параметров очевиден из кода. https://github.com/ydb-platform/ydb-nodejs-sdk/blob/main/src/retries.ts#L7-L16
`backoffCeiling` — максимальное значение экспоненты,
`backoffSlotDuration` — значение в миллисекундах, на которое умножается экспоненциальный коэффициент.
