### ISSUE TITLE
Отказаться от устаревшего пакета grpc

### ISSUE THREAD

**Issue by nikolaymatrosov** [ydb-platform/ydb-nodejs-sdk#128]
[grpc](https://www.npmjs.com/package/grpc) уже с апреля 2021 устарел и рекомендовано вместо него использовать [@grpc/grpc-js](https://www.npmjs.com/package/@grpc/grpc-js)

**Comment by rrewll** [comment]
В версии 3.0.0 перешли на [@grpc/grpc-js](https://www.npmjs.com/package/@grpc/grpc-js).
