### ISSUE TITLE
Авторизация с помощью IAM-токена : пример не работает

### ISSUE THREAD

**Issue by gayratv** [ydb-platform/ydb-nodejs-sdk#129]
Помогите пожалуйста понять почему не работает стандартный пример из SDK: Авторизация с помощью IAM-токена

Вот мой код (несколько строк): 
https://github.com/gayratv/ydb-auth-token

**Comment by gayratv** [comment]
Проблему нашел.
В примере SDK предлагается написать так:
```const authService = new TokenAuthService(accessToken, databaseName);```

чтобы работало надо писать так:
```const authService =new TokenAuthService(process.env.YDB_ACCESS_TOKEN_CREDENTIALS, dbName, getNewSslCredentials());```

Но тут сразу возникает проблема: getNewSslCredentials - это внутренняя функция.

Чтобы пример работал надо :
1. в env определить переменную YDB_ACCESS_TOKEN_CREDENTIALS и туда положить IAM токен.
2.  В коде записать так:
const authService = getCredentialsFromEnv(entryPoint, databaseName, logger);

**Comment by tsufiev** [comment]
@gayratv большое спасибо за user acceptance testing наших сниппетов! Похоже, действительно, в них вкралась некоторая неточность.

**Comment by tsufiev** [comment]
@rrewll Олег, поправишь сниппеты так, чтобы их действительно можно было использовать в реальном коде?

**Comment by rrewll** [comment]
В рамках [этого коммита](https://github.com/ydb-platform/ydb-nodejs-sdk/commit/40523f796f281bbba6de23c6c86013d1bb794d0b) и версии 2.9.2 эта проблема починена.
