### ISSUE TITLE
Allow to pass SSL root certificates for IamAuthService ssl clients

### ISSUE THREAD

**Issue by tsufiev** [ydb-platform/ydb-nodejs-sdk#138]
It seems that the only use of that class is IamAuthService, which subclasses it. I do not know, why it does work without passing rootCertificates into grpc.credentials.createSsl() - but I am not sure whether that always be true. We need to check this assumption with our YDB colleagues, if that happened by sheer luck, pass rootCertificates here as well.

_Originally posted by @tsufiev in https://github.com/ydb-platform/ydb-nodejs-sdk/pull/135#discussion_r807896369_

**Comment by rrewll** [comment]
This behavior was implemented in v3.0.0: #135.
E.g.:
```
const sslCredentials = {rootCertificates: ..., ...};
const saCredentials = getSACredentialsFromJson(saKeyFile);
const authService = new IamAuthService(saCredentials, sslCredentials);
```
