### ISSUE TITLE
How to get Date from YDB

### ISSUE THREAD

**Issue by gayratv** [ydb-platform/ydb-nodejs-sdk#140]
запустил session.executeQuery на таблицу в которой одна из колонок имеет тип Date

в результате получил columns в котором указан тип 48 (Date)
и rows в котором для соответсвующей колонки написано :

{
  "uint32Value": 17596
}

В types.ts есть специальная функция objectFromValue (она без export) которая конвертирует такое поле в date
https://github.com/ydb-platform/ydb-nodejs-sdk/blob/main/src/types.ts#L436

также нашел функцию:
function convertYdbValueToNative(

Скажите пожалуйста что надо сделать чтобы получить нативный date из базы ?
Видимо после executeQuery  надо на результат вызвать какую то функцию ?

**Comment by gayratv** [comment]
Нашел функцию TypedData.createNativeObject - которая выдает объект
Надо ей пользоваться ?

**Comment by rrewll** [comment]
Да, правильный способ - это воспользоваться функцией TypedData.createNativeObjects.
Пример:
```js
const query = 'SELECT Date("2022-01-01") AS date_value;';
const response = await session.executeQuery(query);
const result = TypedData.createNativeObjects(response.resultSets[0]); // [{dateValue: new Date('2022-01-01:00:00:00Z')}]
```
