### ISSUE TITLE
dropTable не возвращает значение результата

### ISSUE THREAD

**Issue by gayratv** [ydb-platform/ydb-nodejs-sdk#141]
Вызов dropTable на отсутствующей таблице не возвращает никакой ошибки

```
await driver.tableClient.withSession(async (session) => {
    // public async dropTable(tablePath: string, settings?: DropTableSettings): Promise<void> {
    try {
      await session.dropTable(`api/oGRKpx06wJkh`);
    } catch (e) {
      console.log('Ошибка');
    }
  });

```

**Comment by gayratv** [comment]
Когда вызваю что то , то хочется понять - прошло или нет ?
Допустим я drop вызвал - и в этот момент сеть пропала, квота пробита - или что то еще случилось.

Хотелось бы получить 3 вида результатов:
1. success
2. error - описание ошибки
3. попытка удалить несуществующую таблицу

**Comment by tsufiev** [comment]
> Когда вызваю что то , то хочется понять - прошло или нет ? Допустим я drop вызвал - и в этот момент сеть пропала, квота пробита - или что то еще случилось.
> 
> Хотелось бы получить 3 вида результатов:
> 
> 1. success
> 2. error - описание ошибки
> 3. попытка удалить несуществующую таблицу

См. предложенное решение в связанном PR.

**Comment by gayratv** [comment]
Красиво!

Еще бы небольшой комментарий добавить в dropTable как пользоваться - было бы вообще замечательно!
А то каждый раз исходный код ковырять - много времени уходит :)

**Comment by tsufiev** [comment]
> Красиво!
> 
> Еще бы небольшой комментарий добавить в dropTable как пользоваться - было бы вообще замечательно! А то каждый раз исходный код ковырять - много времени уходит :)

Ok, добавил небольшой docstring к определению dropTable. Здесь TypeScript должен еще помогать - с помощью инструментов code completion и подсказки, какие аргументы у dropTable / у конструктора DropTableSettings.
