### ISSUE TITLE
OPENSSL_API_COMPAT expresses an impossible API compatibility level

### ISSUE THREAD

**Issue by vladkolotvin** [ydb-platform/ydb-nodejs-sdk#145]
Библиотека не устанавливается на MacOs

Прикладываю лог.
[2022-05-01T21_27_23_556Z-debug-0.log](https://github.com/ydb-platform/ydb-nodejs-sdk/files/8599792/2022-05-01T21_27_23_556Z-debug-0.log)

**Comment by vladkolotvin** [comment]
`% node --version
v18.0.0`

**Comment by vladkolotvin** [comment]
Попробовал собрать docker образ alpine и buster (debian). Там такая же ошибка. Т.е. сейчас библиотека полностью не работоспособна.

**Comment by nikolaymatrosov** [comment]
Си-версия grpc не поддерживается. Не удивительно, что она не заработала на Node 18. Попробуйте сдаунгрейдить рантайм до Node 16.

**Comment by vladkolotvin** [comment]
> Си-версия grpc не поддерживается. Не удивительно, что она не заработала на Node 18. Попробуйте сдаунгрейдить рантайм до Node 16.

Спасибо, да, уже сам перебрал версии ноды и нашел, что на 16 ставится. 
А вообще [тут](https://www.npmjs.com/package/grpc) пишут, что последняя поддерживаемая версия ноды 14.

**Comment by nikolaymatrosov** [comment]
Этот репозиторий с SDK тестируется с 10 по 16 версии.

https://github.com/ydb-platform/ydb-nodejs-sdk/blob/main/.github/workflows/ci.yml#L24

**Comment by tsufiev** [comment]
> Попробовал собрать docker образ alpine и buster (debian). Там такая же ошибка. Т.е. сейчас библиотека полностью не работоспособна.
> 
> Надеюсь, что в #146 помогут.

Выпустили версию 3.1.0, в ней отсутствуют зависимости от старой библиотеки grpc, попробуйте.

**Comment by vladkolotvin** [comment]
> > Попробовал собрать docker образ alpine и buster (debian). Там такая же ошибка. Т.е. сейчас библиотека полностью не работоспособна.
> > Надеюсь, что в #146 помогут.
> 
> Выпустили версию 3.1.0, в ней отсутствуют зависимости от старой библиотеки grpc, попробуйте.

После обновления появились проблемы с импортом. Не знаете, с чем может быть связано?
```
import { getCredentialsFromEnv, Driver } from 'ydb-sdk';
                                ^^^^^^
SyntaxError: Named export 'Driver' not found. The requested module 'ydb-sdk' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'ydb-sdk';
const { getCredentialsFromEnv, Driver } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async loadESM (node:internal/process/esm_loader:85:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)

Node.js v18.0.0
```

**Comment by tsufiev** [comment]
Импортируете при этом не в TypeScript-приложение? Предполагаю, что целевой рантайм всё-таки Node.js приложение, но при этом используются esm-модули вместо нативных commonJS, всё так?

**Comment by vladkolotvin** [comment]
> Импортируете при этом не в TypeScript-приложение? Предполагаю, что целевой рантайм всё-таки Node.js приложение, но при этом используются esm-модули вместо нативных commonJS, всё так?

Верно. У меня node.js приложение. Использую esm-модули.
