### ISSUE TITLE
Разница между TableClient.withSessionRetry и withRetries

### ISSUE THREAD

**Issue by vladkolotvin** [ydb-platform/ydb-nodejs-sdk#149]
В чём отличие этих методов? Какой лучше использовать?

**Comment by tsufiev** [comment]
TableClient.withSessionRetry (он же SessionPool.withSessionRetry) пересоздаёт сессию и выполняет переданную функцию в ней заново (с максимальным числом попыток `maxRetries`) при получении ошибок BadSession или SessionBusy. А обёртка withRetries перевыполняет переданную функцию с различными вариантами задержки (мгновенное перевыполнение / экспоненциально растущая задержка) в зависимости от типа полученной ошибки, но сессию при этом не пересоздаёт. Рекомендация по использованию такова: если нужны и ретраи по исправляемым ошибкам (т.е. тем ошибкам, которые имеет смысл ретраить и для которых предназачен хелпер `withRetries` / декоратор `retryable`), и ретраи с пересозданием сессии, то стоит оборачивать блок запросов / функцию внутри с помощью withRetries, а снаружи - с помощью withSessionRetry.

**Comment by vladkolotvin** [comment]
Т.е. как-то так?
```
await driver.tableClient.withSessionRetry(async (session) => {
    return await withRetries(async () => {
        const query = `...`;
        const preparedQuery = await session.prepareQuery(query);
        return await session.executeQuery(preparedQuery);
    });
});
```
