### ISSUE TITLE
memory leak in v3

### ISSUE THREAD

**Issue by akunafin** [ydb-platform/ydb-nodejs-sdk#157]
I've created a simple nodejs app with express:

```
require('dotenv').config();
const express = require('express');
const app = express();
var ydb_sdk = require('ydb-sdk');

app.use(express.urlencoded({ extended: true }));
app.use(express.json());
app.get('/api/player/get', async (req, res) => {
  let result = await getPlayer();
  res.send(result);
});
app.listen(3000);

async function getPlayer() {
  let query = 'select * from Players where id = 10';
  const logger = ydb_sdk.getLogger();
  const authService = ydb_sdk.getCredentialsFromEnv(logger);
  const database = process.env.DATABASE;
  const endpoint = process.env.ENDPOINT;
  const driver = new ydb_sdk.Driver({endpoint, database, authService, logger});
  if (!(await driver.ready(10000))) {
    process.exit(1);
  }
  let result
  await driver.tableClient.withSession(async (session) => {
    const preparedQuery = await session.prepareQuery(query);
    const response = await session.executeQuery(preparedQuery);
    const response_json = response.toJSON(); 
    result = response_json;
  });
  return result;
}
```

After every HTTP GET I see an app memory usage increase. After several requests I did a heap snapshot and see that there are same size objects accumulating:
<img width="861" alt="image" src="https://user-images.githubusercontent.com/71261156/168317376-2ff2cf6c-db12-44f2-9a55-2f7e83aba0fc.png">

node version: v16.14.0
ydb-sdk version: 3.1.1

**Comment by nikolaymatrosov** [comment]
Try not to recreate `authService` on every call as it is meant to be a singleton. It spawns timeout callbacks that renew the IAM token in the background. This behavior leads to a memory leak. But it is not an SDK problem.

**Comment by akunafin** [comment]
I tried to declare logger and authService globally in order not to recreate it on every call as you suggested, but it doesn't change the behavior.

**Comment by nikolaymatrosov** [comment]
Try to move `Driver` creation to the global scope too. Or call the `destroy` method in the end if you want to recreate it on every request.

**Comment by akunafin** [comment]
It looks like moving the driver to global scope solved the leak. Does it mean that I should always have logger, authService and driver to be declared in global scope?
Thanks for your help!

**Comment by tsufiev** [comment]
> It looks like moving the driver to global scope solved the leak. Does it mean that I should always have logger, authService and driver to be declared in global scope?
> Thanks for your help!

Since JS/Node.js don't have a notion of 'destructor', like in C++, you have to manually call `driver.destroy()` (as Nikolay mentioned earlier) every time new `driver` variable leaves the set of top-level accessible objects and thus is about to be reclaimed by garbage collector. The `driver.destroy()` method takes care of cancelling periodic callbacks which otherwise gradually increase memory consumption in your application.

So, there are 2 options: either every time you're about to throw away `Driver` instance to call its `destroy()` method, or keep the `Driver` instance high enough in the call stack, so that it won't be thrown away.
