### ISSUE TITLE
streamReadTable и createNativeObjects на только что созданной таблице

### ISSUE THREAD

**Issue by OSA413** [ydb-platform/ydb-nodejs-sdk#170]
Чтение из только что созданной таблицы с созданием объектов с помощью createNativeObjects падает с ошибкой `TypeError: Cannot destructure property 'rows' of 'resultSet' as it is undefined.`

Минимальный воспроизводимый пример:
```
public runSession<T>(callback: (session: Session) => Promise<T>, timeout?: number) {
    return this.driver.tableClient.withSession(callback, timeout);
}

await this.ydb.runSession(async s => {
    await s.createTable(`main/test`,
        new TableDescription()
            .withColumns(
                new Column("name", Types.optional(Types.STRING))
            ).withPrimaryKeys("name")
     )
            
    let set: Ydb.IResultSet;
    await s.streamReadTable(`main/test`, res => {set = res.resultSet})
    console.log(set) //undefined
    return User.createNativeObjects(set) as User[]
})
```

Временная починка: добавить `?? {}` после `set` при вызове `createNativeObjects`

```
return User.createNativeObjects(set ?? {}) as User[]
```

И тогда функция вернёт ожидаемый пустой список.

Возможно стоит возвращать внутри callback у `streamReadTable` пустой объект или добавить проверку на такое в самом `createNativeObjects` https://github.com/ydb-platform/ydb-nodejs-sdk/blob/main/src/types.ts#L655

**Comment by tsufiev** [comment]
@OSA413 Скажите, а как у вас получилось передать set, который по типа `IResultSet | undefined | null` в `TypedData.createNativeObjects(resultSet: IResultSet)`, который не принимает `undefined` :)? У меня вот так IDE ругается (и компилятор должен):

<img width="1015" alt="Screenshot 2022-08-12 at 15 37 06" src="https://user-images.githubusercontent.com/1240006/184355572-d1eb516d-3854-439f-aabd-2da5a8cc4ff7.png">

**Comment by OSA413** [comment]
@tsufiev это, скорее всего, последствие поздно обнаруженного параметра `strictNullChecks: false` или чего-то ещё в `tsconfig.json`, который nest-js делает по умолчанию, из-за чего мне удалось такое сделать в попытках упростить код взаимодействия с SDK.

**Comment by tsufiev** [comment]
Понял. Тогда этот тикет я закрою - проблему выше должен сам Typescript ловить согласно сигнатуре метода.
