### ISSUE TITLE
Referencing package.json breaks minification builds like esbuild

### ISSUE THREAD

**Issue by esseswann** [ydb-platform/ydb-nodejs-sdk#173]
This line tries to find the package.json by an absolute path which might not be available if the build is fully minified and tree-shaked during compile time.
https://github.com/ydb-platform/ydb-nodejs-sdk/blob/5b9a68cb6e49344d2013cc82df28a8e17ea405e7/src/version.ts#L7
It should either be referenced in the compile time (macro or otherwise) or not depend on it during runtime

**Comment by DavyJohnes** [comment]
@tsufiev I think this is critical, since it completely blocks usage of sdk for environments with bundled code.

**Comment by DavyJohnes** [comment]
Here is temporary solutions which solves issue in webpack:
```
           {
                test: /node_modules\/ydb-sdk\/build\/cjs\/version\.js$/,
                loader: 'string-replace-loader',
                options: {
                    search: 'path_1.default.join(getRelTopLevelPath(), \'package.json\')',
                    replace: '\'../../package.json\'',
                },
            },
```

**Comment by esseswann** [comment]
It seems to be breaking fruther here
https://github.com/ydb-platform/ydb-nodejs-sdk/blob/main/src/ssl-credentials.ts#L7
for the same reason
