### ISSUE TITLE
Ошибка - инициализированный драйвер вылетает с ошибкой

### ISSUE THREAD

**Issue by gayratv** [ydb-platform/ydb-nodejs-sdk#175]
Для воспроизведения ошибки надо запустить простой express сервер (запускался на VPS), проинициализировать Driver YDB (в моем случае с помощью SA_KEY_FILE), подождать несколько часов.
Код:
```
(async () => {
  await initDbLocal();
})();

app.get('/', (_req, res) => {  res.send(`Hello World! test app\n`);});

app.listen(port, () => {   console.log(`Example app listening on port ${port}`); });

```
Через несколько часов сервер падает с ошибкой.
Видно что сервер запустился, инициализировался, отработал обращение по curl, потом я его оставил на несколько часов и он упал.

```
{"level":30,"time":1659495396676,"pid":5519,"hostname":"cp2","msg":"Driver initializing..."}
Example app listening on port 3020
{"level":30,"time":1659495396847,"pid":5519,"hostname":"cp2","msg":"Done"}
/apptest
/apptest
/apptest
/var/www/makeupkitchen.ga/node/node_modules/@grpc/grpc-js/src/call.ts:81
  const error = new Error(message);
                ^
Error: 14 UNAVAILABLE: Stream refused by server
    at Object.callErrorFromStatus (/var/www/makeupkitchen.ga/node/node_modules/@grpc/grpc-js/src/call.ts:81:17)
    at Object.onReceiveStatus (/var/www/makeupkitchen.ga/node/node_modules/@grpc/grpc-js/src/client.ts:352:36)
    at Object.onReceiveStatus (/var/www/makeupkitchen.ga/node/node_modules/@grpc/grpc-js/src/client-interceptors.ts:462:34)
    at Object.onReceiveStatus (/var/www/makeupkitchen.ga/node/node_modules/@grpc/grpc-js/src/client-interceptors.ts:424:48)
    at /var/www/makeupkitchen.ga/node/node_modules/@grpc/grpc-js/src/call-stream.ts:330:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at Client.makeUnaryRequest (/var/www/makeupkitchen.ga/node/node_modules/@grpc/grpc-js/src/client.ts:324:26)
    at IamTokenService.rpcImpl (/var/www/makeupkitchen.ga/node/node_modules/ydb-sdk/build/cjs/utils.js:71:20)
    at IamTokenService.rpcCall (/var/www/makeupkitchen.ga/node/node_modules/protobufjs/src/rpc/service.js:94:21)
    at executor (/var/www/makeupkitchen.ga/node/node_modules/@protobufjs/aspromise/index.js:44:16)
    at new Promise (<anonymous>)
    at Object.asPromise (/var/www/makeupkitchen.ga/node/node_modules/@protobufjs/aspromise/index.js:28:12)
    at IamTokenService.rpcCall (/var/www/makeupkitchen.ga/node/node_modules/protobufjs/src/rpc/service.js:86:21)
    at IamTokenService.Create (/var/www/makeupkitchen.ga/node/node_modules/ydb-sdk-proto/proto/bundle.js:92967:37)
    at IamAuthService.sendTokenRequest (/var/www/makeupkitchen.ga/node/node_modules/ydb-sdk/build/cjs/credentials.js:88:39)
    at IamAuthService.updateToken (/var/www/makeupkitchen.ga/node/node_modules/ydb-sdk/build/cjs/credentials.js:92:41) {  code: 14,
  details: 'Stream refused by server',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
```

**Comment by nikolaymatrosov** [comment]
Ошибки с типом `UNAVAILABLE` вам нужно ретраить. Подробнее тут https://github.com/ydb-platform/ydb-nodejs-sdk/blob/main/src/retries.ts

**Comment by gayratv** [comment]
Николай, retry тут точно никак не поможет. До старта сервера express драйвер инициализируется:
` driver = new Driver`
далее я его использую там где нужно

Проблема в том, что после инициализации драйвера - если к нему не было обращений он вылетает с ошибкой в промежуток приблизительно от 1 до 4 часов с момента бездействия.

Тимур подсказал, что такая ошибка ловится событием process.on
Эксперимент показал, что если поставить обработчик на это событие и сделать driver.Destroy и по новой инициализировать драйвер - то проблема лечится.

Но так вообще то не должно быть (на мой взгляд)

Из отпуска вернусь код, решающий эту проблему опубликую - но process.on - по моему плохой подход

**Comment by nikolaymatrosov** [comment]
Ну к ошибкам получения токена это тоже относится. `UNAVAILABLE` там тоже надо ретраить.

**Comment by gayratv** [comment]
Смотрите, есть голый драйвер, работающий в момент инициализации.
Дальше он просто бездействует несколько часов (от 1 до 4 часов) и падает с ошибкой сам по себе - я его не трогаю.
Тут по идее driver должен выбрасывать некое событие, которое я мог бы обработать - потому что ретрай не на что навешивать

**Comment by gayratv** [comment]
Собрал отдельный проект с одним файлом для иллюстрации ошибки

https://github.com/gayratv/ydb-driver-fail-test

**Comment by zeruk** [comment]
Здравствуйте! Спасибо за репозиторий, повторил ошибку, но, судя по всему, это именно проблема обновления токена. У меня данная ошибка в течение четырех часов не происходила, но произошла при экспирации токена (примерно 12 часов).

**Comment by gayratv** [comment]
Весь вопрос как с этим бороться ?
process.on наверно не слишком хорошее решение

Если запускать таймер на некоторое время и принудительно разрушать/создавать драйвер - то тут вопрос на какое время программировать таймер ?

У меня падало в период от 1 до 4 часов.

Можно конечно таймер поставить на полчаса, но не понимая внутреннего механизма легко получить ту же самую гранату :)

По хорошему если драйвер желает просто тупо упасть сам по себе без всяких обращений к нему он по хорошему должен был бы для начала какое нибудь сообщение выкинуть

**Comment by slaviknnov** [comment]
Тоже очень интересует как правильно решить подобную проблему

**Comment by zeruk** [comment]
@slaviknnov Если у вас есть проект, на котором встречалась данная ошибка, то можете протестировать pull request #193. Этот PR должен помочь с такими проблемами

**Comment by zeruk** [comment]
@gayratv вышла новая версия ydb-sdk@3.5.0, протестируйте, пожалуйста, что она помогла с вашей проблемой

**Comment by zeruk** [comment]
@slaviknnov @gayratv Подскажите, решилась ли ваша проблема? тестировали ли вы релизы `ydb-sdk@3.4.5` и выше?

**Comment by gayratv** [comment]
> @slaviknnov @gayratv Подскажите, решилась ли ваша проблема? тестировали ли вы релизы `ydb-sdk@3.4.5` и выше?

В проекте, указанном выше :
https://github.com/gayratv/ydb-driver-fail-test

поправил пакет до :

  "ydb-sdk": "^4.0.0"
  
 на Yandex cloud развернул сервер из образа Node, проект запустил, завтра посмотрю - отвалится или нет ?

**Comment by gayratv** [comment]
> @slaviknnov @gayratv Подскажите, решилась ли ваша проблема? тестировали ли вы релизы `ydb-sdk@3.4.5` и выше?

Проблема не исчезла.
К сожалению не догадался вывести время,
Оставил сервер на ночь, через сутки получил:

TimeoutExpired [Error]: Timeout of 10000ms has expired
    at Timeout._onTimeout (/var/ydb/ydb-driver-fail-test/node_modules/ydb-sdk/build/cjs/src/utils.js:47:20)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7) {
  issues: []
}

Сам сервер, который запускал доступен на github (всего несколько строк)
Итого: если драйвер инициализировать и оставить, то он крашит приложение (по крайней мере в течение суток)

**Comment by zeruk** [comment]
@gayratv Это полный текст ошибки? Таймаут можно поймать в других местах. Выглядит так, что изначальная проблема ушла. Тоже запустил этот тест, жду результатов

**Comment by gayratv** [comment]
@zeruk Илья, добрый день, да, полный.

Как видно из текста программы
https://github.com/gayratv/ydb-driver-fail-test

инициализируется драйвер YDB, запускается express с двумя тестовыми роутами: первый "Hello", второй - произвольная выборка из YDB

Все это оставляется на сутки.

Через сутки видим упавшее приложение (сервер вообще не трогался в течение суток)

Я ожидал что сервер будет живым и вернет выборку из YDB

**Comment by zeruk** [comment]
@gayratv Добрый день! Похоже, что обнаружил проблему. Не было ретраев у сервисов авторизации. Проверьте, проблема должна пропасть в версии 4.6.0

PR с изменениями: https://github.com/ydb-platform/ydb-nodejs-sdk/pull/271

**Comment by zeruk** [comment]
Done in #271
