### ISSUE TITLE
feat: divide package into two: esm and cjs

### ISSUE THREAD

**Issue by zeruk** [ydb-platform/ydb-nodejs-sdk#212]
# Feature Request

## Describe the Feature Request

It will possibly decrease package size as much as twice, but will complicate build and release process

## Additional Context

If the feature request is approved, would you be willing to submit a PR?
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by Zork33** [comment]
this idea is a part of #322

**Comment by Zork33** [comment]
Consider this article https://www.typescriptlang.org/docs/handbook/modules/appendices/esm-cjs-interop.html  At the moment we only thing that differs those two in context of SDK is "default" export
