### ISSUE TITLE
Как заставить это работать

### ISSUE THREAD

**Issue by guideblade** [ydb-platform/ydb-nodejs-sdk#335]
https://github.com/ydb-platform/ydb-nodejs-sdk/blob/0b1c448a7dee0316b60ee4ad8c40c96ca73da9b0/examples/basic-example-v1/index.ts#L263

Откуда run() берет logger, endpoint и database? Где мне их задать?
Он даже вызывается без параметров... просто main(run)... В utils.ts я тоже ничего не нашел... Вот бы там были константы endpoint и database...

**Comment by guideblade** [comment]
> Очевидно из функции `main`. Значения для этих переменных извлекаются из аргументов командной строки, передаваемых при запуске, вот [тут](https://github.com/ydb-platform/ydb-nodejs-sdk/blob/0b1c448a7dee0316b60ee4ad8c40c96ca73da9b0/examples/utils.ts#L24-L27).
> 
> Пример команд для запуска есть в [README](https://github.com/ydb-platform/ydb-nodejs-sdk#run-basic-example-script).

Эх, я уже понял... но теперь у меня проблема с инициализацией драйвера... Просто пишет driver has not become ready in 10000ms (FATAL). Что с этим делать?

**Comment by Zork33** [comment]
А к какой БД надо подключиться, к локальной (в контейнере) или в Облаке? 10 сек очевидно говорит о том, что найти БД не получается

**Comment by guideblade** [comment]
> А к какой БД надо подключиться, к локальной (в контейнере) или в Облаке? 10 сек очевидно говорит о том, что найти БД не получается

В облаке. Извините за то, что я такой тупой, просто я вообще не шарю в node,js, а преподователь использовать Python запретил(( Может есть кто поможет?

**Comment by guideblade** [comment]
Может у меня --connection-string неверная? Только щас заметил, что там почему то "?database" два раза встречается

**Comment by Zork33** [comment]
Да, давай помогу разобраться.  Но, с сожалению, только завтра.  Для оперативности наверное лучше перейти в Телеграмм - моя учетка [Zork33](https://t.me/Zork33)

**Comment by guideblade** [comment]
> Да, давай помогу разобраться. Но, с сожалению, только завтра. Для оперативности наверное лучше перейти в Телеграмм - моя учетка [Zork33](https://t.me/Zork33)

Спасибо вам заранее, сейчас добавлю

**Comment by Zork33** [comment]
Инструкция для подключения с локальной машины к облачной YDB - https://github.com/Zork33/todoer/blob/main/README.md

**Comment by Zork33** [comment]
Инструкция для подключения с локальной машины к облачной YDB - https://github.com/Zork33/todoer/blob/main/README.md
