### ISSUE TITLE
Выборка данных, где в качестве параметра используется переменная типа String, всегда возвращает пустой результат

### ISSUE THREAD

**Issue by ciferblat** [ydb-platform/ydb-nodejs-sdk#67]
Версия библиотеки 1.9.0

### Описание ошибки

Допустим, имеем таблицу `tbl` с колонкой `id` типа `String`:

id (String) | value (Double)
------------ | -------------
abc | 10
efg | 20

Запрос вида:

```typescript

class Entity extends TypedData {
  @declareType({ typeId: Ydb.Type.PrimitiveTypeId.STRING })
  id: string;

  @declareType({ typeId: Ydb.Type.PrimitiveTypeId.DOUBLE})
  value: number;
}

// --------

const query = `

      DECLARE $id AS String;

      SELECT id, value
        FROM \`tbl\`
       WHERE id = $id;
    `;

// --------

const preparedQuery = await session.prepareQuery(query);
const paramEntity = new Entity({id: 'efg'}); 
const queryResult = await session.executeQuery(
              preparedQuery,
              {$id: paramEntity.getTypedValue('id')} // value.bytesValue присваивается значение 'efg'
            );
```
вернёт пустой результат:
```typescript
queryResult.resultSets[0].rows.length === 0
-> true
```
хотя должен был вернуть вторую строчку таблицы.

### Предварительное решение

Удалось корректно получать данные из таблицы, если дополнительно преобразовывать `value.bytesValue` в base64, например так:

```typescript
const paramEntity = new Entity({id: Buffer.from('efg').toString('base64')}); 
```

В [коде для bytesValue](https://github.com/yandex-cloud/ydb-nodejs-sdk/blob/6c34ecc41f4e84ebabfa905309b07bc6832f6be1/src/types.ts#L63) есть обратное преобразование при получении данных с сервера, но нет при передаче параметров запроса на сервер (см. функцию [preparePrimitiveValue](https://github.com/yandex-cloud/ydb-nodejs-sdk/blob/6c34ecc41f4e84ebabfa905309b07bc6832f6be1/src/types.ts#L112))

**Comment by nikolaymatrosov** [comment]
Нет простого способа определить нуждается ли строка в преобразовании или вы ее уже подготовили и сами сконвертировали в base64. Чтобы не возникало таких проблем можно просто вместо типа `String` пользоваться типом `Utf8`.

**Comment by tsufiev** [comment]
@ciferblat Прошу прощения за не самый быстрый ответ, но мы пофиксили проблему в https://github.com/ydb-platform/ydb-nodejs-sdk/pull/177/commits/b8034a8fc2903b5d6b02d0927ec58b2d9032da3e

Действительно, работа с типом Types.STRING велась некорректно и для правильной работы надо было бы сначала перед отправкой данных в YDB преобразовать строку в Buffer: `Buffer.from(value)`. Теперь Types.STRING объявлен deprecated-типом, рекомендуется переходить на Types.BYTES, который всегда работает с Buffer, а преобразование из/в строку должно выполняться на стороне клиентского кода, во избежание неоднозначностей выбора кодировки.
