### ISSUE TITLE
lost dbName attribute in AnonymousAuthService

### ISSUE THREAD

**Issue by goshander** [ydb-platform/ydb-nodejs-sdk#90]
In debug mode with ydb docker container dbName is not specified in auth service and i get error when i try to make SELECT request

I created simple fix snippet with below code and it works fine
Maybe I use wrong auth service with docker container

---

При отладке в тестовой среде через docker контейнер при использовании auth сервиса я получаю ошибку, когда пытаюсь выполнить SELECT запрос

Попробовал применить небольшой фикс ниже и все заработало отлично
Возможно я использую неверный auth сервис для авторизации с docker, поправьте меня

---

**environement**
node-container: `node:14.17.6-buster-slim`
ydb-sdk: `2.5.0`

**error**
```
Cannot find table 'db.[request]' because it does not exist or you do not have access permissions. Please check correctness of table path and user permissions.
```

**fix-snippet**
```js
    authService = new AnonymousAuthService()
    authService.getAuthMetadata = function () {
      const grpc = require('grpc')
      const metadata = new grpc.Metadata()
      metadata.add('x-ydb-database', '/local')
      return Promise.resolve(metadata)
    }
```

**Comment by tsufiev** [comment]
@goshander Thanks for the issue and the fixing snipped! I've made a more thorough fix https://github.com/ydb-platform/ydb-nodejs-sdk/pull/94, wanna take a look?

**Comment by goshander** [comment]
Looks good, work as expected 👍👍👍

**Comment by goshander** [comment]
#94 merged
