### ISSUE TITLE
bulkUpsert не реализован

### ISSUE THREAD

**Issue by Ulibka68** [ydb-platform/ydb-nodejs-sdk#92]
Если я правильно понял - то bulkUpsert должен быть в объекте Session (по аналогии с executeQuery)
Просьба добавить bulkUpsert  в Session 

Если я неправильно понял - то напишите пожалуйста способ вызова bulkUpsert

**Comment by tsufiev** [comment]
Метод `bulkUpsert` скоро появится https://github.com/ydb-platform/ydb-nodejs-sdk/pull/99
