### ISSUE TITLE
withSession и withRetries  вопрос

### ISSUE THREAD

**Issue by Ulibka68** [ydb-platform/ydb-nodejs-sdk#98]
Для получения сессии есть два метода:

withSession и
withSessionRetry

единственное отличие этих методов - это параметр maxRetries, который присутствует во втором методе.
При наличии параметра maxRetries служебный метод _withSession пробует исполнить запрос еще раз не более maxRetries раз с другой сессией.

В примерах Тимур использует withSession и оборачивает исполненение запроса в функцию withRetries которая по умолчанию устанавливает maxRetries=10 и далее вызывается метод retry класса RetryStrategy

Скажите пожалуйста в чем отличие работы withSessionRetry с установленыым параметром maxRetries =10 от работы RetryStrategy.retry  ?

Timur Sufiev, [17.11.2021 14:49]
[В ответ на Гайрат Власов]
в том, что RetryStrategy.retry делает ретраи на errors.Unavailable, errors.Aborted, errors.NotFound и errors.Overloaded (для последней бэкоффы больше), а withSession делает ретраи только на 2 ошибки: BadSession и SessionBusy - и без бэкоффов б) RetryStrategy.retry не пересоздает сессию в случае ошибок

Timur Sufiev, [17.11.2021 14:50]
декоратором @retryable, вызывающим RetryStragegy.retry, обёрнуты многие методы базовых классов работы с таблицами, в то время как withSession предполагает более высокий уровень - на куски кода, которые, если пофейлятся, должны быть перевыполнены заново в рамках новой сессии

Timur Sufiev, [17.11.2021 14:49]
[В ответ на Гайрат Власов]
в том, что RetryStrategy.retry делает ретраи на errors.Unavailable, errors.Aborted, errors.NotFound и errors.Overloaded (для последней бэкоффы больше), а withSession делает ретраи только на 2 ошибки: BadSession и SessionBusy - и без бэкоффов б) RetryStrategy.retry не пересоздает сессию в случае ошибок

Timur Sufiev, [17.11.2021 14:50]
декоратором @retryable, вызывающим RetryStragegy.retry, обёрнуты многие методы базовых классов работы с таблицами, в то время как withSession предполагает более высокий уровень - на куски кода, которые, если пофейлятся, должны быть перевыполнены заново в рамках новой сессии

Гайрат Власов, [17.11.2021 15:04]
[В ответ на Timur Sufiev]

Скажите пожалуйста - почему на executeQuery Вы не поставили @retryable - а обрабатываете его отдельно в рамках withRetries ?

Правильно ли я понимаю что сам ретрай нужен потому, что на базу может быть установлено ограничение по пропускной способности, RU/с и в случае большой нагрузки на запрос может прийти отказ - поэтому его может так случиться что запрос надо повторить без изменений. 
Почему тогда в ретраях Вы не ставите некий таймаут?

Если в момент передачи запроса пропадет интернет соединение (мобильный телефон) - то это значит что прервется сессия ?
Следует ли из этого что надо совместно использовать withSessionRetry и withRetries ?

**Comment by tsufiev** [comment]
> Скажите пожалуйста - почему на executeQuery Вы не поставили @retryable - а обрабатываете его отдельно в рамках withRetries ?
Причина в том, что executeQuery не является идемпотетнтным запросом в общем случае и его безусловный retry (в случае ошибок, на которые триггерится RetryStrategy.retry) может привести к непредсказуемым результатам.

> Правильно ли я понимаю что сам ретрай нужен потому, что на базу может быть установлено ограничение по пропускной способности, RU/с и в случае большой нагрузки на запрос может прийти отказ - поэтому его может так случиться что запрос надо повторить без изменений.
Задача клиентского приложения - по возможности корректно обрабатывать все виды исключений, которые генерирует сервер. Перегрузка БД запросами - одна из возможных ситуаций, ей соответствует исключение `errors.Overloaded`. В этом случае повтор происходит с увеличенным экспоненциальным таймаутом (см. исходники по `RETRYABLE_ERRORS_SLOW`).

> Почему тогда в ретраях Вы не ставите некий таймаут?
В withSessionRetry действительно не ставится таймаут, т.к. данный ретрай срабатывает только на два типа ошибок - `BadSession` и `SessionBusy`, для которых таймаут не нужен, т.к. следующая попытка будет выполнена в другой сессии.

> Если в момент передачи запроса пропадет интернет соединение (мобильный телефон) - то это значит что прервется сессия ?
Здравый смысл подсказывает, что такое не исключено, но чтобы дать однозначный ответ, необходимо обладать более глубоким знанием сетевого стека, чем то, которым обладаю я. Или провести серию экспериментов :).

> Следует ли из этого что надо совместно использовать withSessionRetry и withRetries ?
Все базовые методы, обернутые в `@retryable`, уже используют ту же машинерию, что и функция `withRetries`. Так что да, когда вы оборачиваете блоки кода, содержащие такие базовые вызовы в `withSessionRetry`, происходит совместное использование двух механизмов ретраев.
